version: '3.4'

services:
  bookly.api:
    image: ${DOCKER_REGISTRY-}booklyapi
    container_name: Bookly.API
    build:
      context: .
      dockerfile: Bookly.API/Dockerfile
    depends_on:
      - bookly-db

  bookly-db:
    image: postgres:latest
    container_name: Bookly.DB
    environment:
        - POSTGRES_DB=bookly
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=thebest1
    volumes:
        - ./.containers/database:/var/lib/postgresql/data
    ports:
        - 5433:5432

  bookly-idp:
    image: quay.io/keycloak/keycloak:latest
    container_name: Bookly.Identity
    command: start-dev --import-realm
    environment:
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
        - ./.containers/identity:/opt/keycloak/data
        - ./.files/bookly-realm-export.json:/opt/keycloak/data/import/realm.json
    ports:
        - 18080:8080